version: '2.1'

services:
  zoo1:
    image: zookeeper:3.5.8
    hostname: zoo1
    networks:
      - tickler-infra-network
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  kafka1:
    image: confluentinc/cp-kafka:5.5.1
    hostname: kafka1
    networks:
      - tickler-infra-network
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1

  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    hostname: redis
    networks:
      - tickler-infra-network
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - ./redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    ports:
      - 6379:6379

  couchbase:
    image: 'couchbase:6.6.1'
    hostname: couchbase
    networks:
      - tickler-infra-network
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    volumes:
      - ./couchbase:/opt/couchbase/var

networks:
  tickler-infra-network:
    name: tickler-infra-network
