server:
  port: 9090
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      kafka:
        binder:
          auto-create-topics: false
          brokers: ${BROKER_HOST:127.0.0.1}:${BROKER_PORT:9092}
        bindings:
          tickleInput:
            consumer:
              startOffset: latest
      bindings:
        tickleInput:
          group: tickle-group
          destination: com.canseverayberk.tickle
        tickleOutput:
          destination: com.canseverayberk.tickle
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}