server:
  port: 9090
spring:
  cloud:
    zookeeper:
      discovery:
        enabled: true
      connect-string: 127.0.0.1:2181
    stream:
      kafka:
        binder:
          auto-create-topics: false
          brokers: 127.0.0.1:9092
        bindings:
          tickleInput:
            consumer:
              startOffset: latest
          tickleRequestInput:
            consumer:
              startOffset: latest
          callbackInput:
            consumer:
              startOffset: latest
      bindings:
        tickleProcessInput:
          group: tickle-group
          destination: tickle.process.integration.test
        tickleProcessOutput:
          destination: tickle.process.integration.test
        tickleRequestInput:
          destination: tickle.request.integration.test
        callbackInput:
          group: callback-group
          destination: tickle.callback.integration.test
  redis:
    hostname: 127.0.0.1
    port: 6379

couchbase:
  host: 127.0.0.1
  username: Administrator
  password: 123456
  bucketName: source

expiry:
  background: couchbase