server:
  port: ${SERVER_PORT:9090}
management:
  server:
    port: ${MANAGEMENT_SERVER_PORT:9091}
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      kafka:
        binder:
          auto-create-topics: false
          brokers: ${BROKER_HOST:127.0.0.1}:${BROKER_PORT:9092}
        bindings:
          tickleProcessInput:
            consumer:
              startOffset: latest
          tickleRequestInput:
            consumer:
              startOffset: latest
      bindings:
        tickleProcessInput:
          group: tickle-group
          destination: tickle.process
        tickleProcessOutput:
          destination: tickle.process
        tickleRequestInput:
          destination: tickle.request
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}

couchbase:
  host: ${COUCHBASE_HOST:127.0.0.1}
  username: ${COUCHBASE_USER:Administrator}
  password: ${COUCHBASE_PASS:123456}
  bucketName: ${COUCHBASE_BUCKET:source}

expiry:
  background: ${EXPIRY_BACKGROUND:couchbase}